"use client"

import React from "react"

import Link from "next/link"

const h=React.createElement

const css=`*{box-sizing:border-box}.app{min-height:100vh;background:#0b0d0c;color:#f4f1e9;font:15px Arial}.nav{height:76px;border-bottom:1px solid #263326;display:flex;align-items:center;justify-content:space-between;padding:0 6vw}.brand{font-size:19px;font-weight:700;color:#f4f1e9;text-decoration:none}.brand i{color:#b8f26d;font-style:normal}.nav a{color:#9eaa99;text-decoration:none;margin-left:22px;font-size:13px}.cta,.button{background:#b8f26d!important;color:#0b0d0c!important;padding:12px 18px;border-radius:99px;font-weight:700;text-decoration:none}.hero{max-width:1320px;margin:auto;min-height:calc(100vh - 76px);padding:8vw 6vw;display:grid;grid-template-columns:1fr 1fr;gap:6vw;align-items:center}.eyebrow{color:#9aae77;text-transform:uppercase;letter-spacing:.16em;font-size:10px}.hero h1{font:clamp(58px,8vw,120px) Georgia;line-height:.88;letter-spacing:-.08em;margin:28px 0}.hero em{color:#b8f26d;font-weight:400}.lede{color:#9eaa99;line-height:1.75;max-width:480px;font-size:17px}.button{display:inline-block;margin-top:26px}.card{border:1px solid #40513a;background:#121a13;padding:14px;animation:rise .8s both}.inner{background:#0b100d;border:1px solid #263326;padding:28px}.top,.foot{display:flex;justify-content:space-between;color:#71806c;font-size:10px}.top{border-bottom:1px solid #263326;padding-bottom:18px}.title{display:flex;justify-content:space-between;align-items:end;margin:34px 0 22px}.title small,.claim small{display:block;color:#71806c;font-size:9px;letter-spacing:.14em}.title h2{font:32px Georgia;margin:8px 0 0}.claim{display:flex;justify-content:space-between;align-items:center;border:1px solid #40513a;background:#152016;padding:15px;margin-top:8px}.claim p{margin:7px 0 0}.claim b{color:#b8f26d;font-size:11px}.foot{border-top:1px solid #263326;margin-top:22px;padding-top:15px}@keyframes rise{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:none}}@media(max-width:800px){.hero{grid-template-columns:1fr;padding-top:55px}.nav nav{display:none}}`

const c=(n,t,s,m)=>h("div",{className:"claim",style:m?{opacity:.55}:{}},h("div",null,h("small",null,"CLAIM / 0"+n),h("p",null,t)),h("b",null,s))

export default function Page(){return h("main",{className:"app"},h("style",{dangerouslySetInnerHTML:{__html:css}}),h("header",{className:"nav"},h(Link,{href:"/",className:"brand"},"Proof",h("i",null,"Shield")),h("nav",null,h("a",{href:"#method"},"The method"),h("a",{href:"#passport"},"Passport"),h(Link,{href:"/auth/register",className:"cta"},"Start proving ↗"))),h("section",{className:"hero"},h("div",null,h("div",{className:"eyebrow"},"Private credentials / public confidence"),h("h1",null,"Proof, ",h("em",null,"not"),h("br"),"exposure."),h("p",{className:"lede"},"A quieter way to prove what you know. ProofShield turns credentials into precise, verifiable claims without asking you to hand over the whole story."),h(Link,{href:"/auth/register",className:"button"},"Create your passport ↗")),h("div",{className:"card"},h("div",{className:"inner"},h("div",{className:"top"},h("span",null,"● ● ●"),h("span",null,"PS / 7D2A·91F4·E1C8")),h("div",{className:"title"},h("div",null,h("small",null,"PRIVACY PASSPORT"),h("h2",null,"Candidate / A81F")),h("span",null,"◈")),c(1,"Python proficiency ≥ Advanced","✓ Shared"),c(2,"Security+ certification","✓ Shared"),c(3,"Private claim locked","⌑ Locked",true),h("div",{className:"foot"},h("span",null,"⌁ Commitment recorded"),h("span",null,"MIDNIGHT / TESTNET"))))),h("section",{id:"method",style:{padding:"100px 6vw",maxWidth:1320,margin:"auto"}},h("div",{className:"eyebrow"},"01 / The method"),h("h2",{style:{font:"clamp(42px,6vw,80px) Georgia",letterSpacing:"-.06em"}},"A proof is a conversation, not a file dump."),h("p",{className:"lede"},"Bring the evidence, find the claims, keep the source private, and let the result travel.")),h("footer",{style:{padding:"28px 6vw",borderTop:"1px solid #263326",color:"#71806c"}},"Proof, not exposure / 2026"))}
