"use client"



export default function Page() {
  
  return (
    
    <main className="proof-app">
    
      <style>{`@keyframes rise{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}@keyframes drift{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}*{box-sizing:border-box}.proof-app{min-height:100vh;background:#0b0d0c;color:#f4f1e9;font-family:Arial,Helvetica,sans-serif;overflow:hidden}.proof-nav{height:76px;border-bottom:1px solid rgba(214,230,189,.14);display:flex;align-items:center;justify-content:space-between;padding:0 clamp(20px,5vw,72px)}.proof-mark{font-weight:700;letter-spacing:-.05em;font-size:18px}.proof-mark span{color:#b8f26d}.proof-nav a{color:#9eaa99;text-decoration:none;font-size:13px;margin-left:24px}.proof-nav .proof-cta{color:#0b0d0c;background:#b8f26d;border-radius:999px;padding:12px 18px;font-weight:700}.proof-hero{max-width:1320px;margin:0 auto;min-height:calc(100vh - 76px);display:grid;grid-template-columns:1fr 1fr;gap:56px;align-items:center;padding:80px clamp(20px,5vw,72px)}.proof-eyebrow{color:#9aae77;font-size:11px;text-transform:uppercase;letter-spacing:.18em}.proof-hero h1{font-family:Georgia,serif;font-size:clamp(58px,8vw,120px);line-height:.9;letter-spacing:-.08em;margin:28px 0;color:#f4f1e9}.proof-hero h1 em{color:#b8f26d;font-weight:400}.proof-lede{max-width:470px;color:#9eaa99;line-height:1.75;font-size:17px}.proof-button{display:inline-block;background:#b8f26d;color:#0b0d0c;text-decoration:none;font-weight:700;border-radius:999px;padding:15px 22px;margin-top:28px}.proof-card{animation:rise .9s cubic-bezier(.16,1,.3,1) both;position:relative;max-width:520px;justify-self:end;border:1px solid rgba(214,230,189,.22);padding:14px;background:#121a13;box-shadow:0 34px 90px -45px rgba(184,242,109,.55)}.proof-card-inner{border:1px solid rgba(214,230,189,.14);padding:28px;background:#0b100d}.proof-top{display:flex;justify-content:space-between;border-bottom:1px solid rgba(214,230,189,.12);padding-bottom:18px;color:#71806c;font-size:10px}.proof-title{display:flex;justify-content:space-between;align-items:flex-end;margin:34px 0 22px}.proof-title small,.proof-claim small{display:block;color:#71806c;font-size:9px;letter-spacing:.16em}.proof-title h2{font:32px Georgia,serif;letter-spacing:-.05em;margin:9px 0 0}.proof-claim{display:flex;justify-content:space-between;align-items:center;border:1px solid rgba(184,242,109,.2);background:rgba(184,242,109,.05);padding:16px;margin-top:8px}.proof-claim p{margin:7px 0 0;font-size:14px}.proof-claim b{color:#b8f26d;font-size:11px}.proof-foot{border-top:1px solid rgba(214,230,189,.12);margin-top:22px;padding-top:16px;color:#71806c;font-size:10px;display:flex;justify-content:space-between}@media(max-width:800px){.proof-hero{grid-template-columns:1fr;padding-top:55px}.proof-card{justify-self:stretch}.proof-nav nav{display:none}.proof-nav a{margin-left:0}}`}</style>style>
    
      <header className="proof-nav"><a className="proof-mark" href="/">Proof<span>Shield</span>span></a>a><nav><a href="#method">The method</a>a><a href="#passport">Passport</a>a><a href="#why">Why it matters</a>a></nav>nav><a className="proof-cta" href="/auth/register">Start proving ↗</a>a></header>header>
    
      <section className="proof-hero"><div><div className="proof-eyebrow">Private credentials / public confidence</div>div><h1>Proof, <em>not</em>em><br/>exposure.</h1>h1><p className="proof-lede">A quieter way to prove what you know. ProofShield turns credentials into precise, verifiable claims without asking you to hand over the whole story.</p>p><a className="proof-button" href="/auth/register">Create your passport ↗</a>a></div>div><div className="proof-card"><div className="proof-card-inner"><div className="proof-top"><span>● ● ●</span>span><span>PS / 7D2A·91F4·E1C8</span>span></div>div><div className="proof-title"><div><small>PRIVACY PASSPORT</small>small><h2>Candidate / A81F</h2>h2></div>div><span>◈</span>span></div>div><div className="proof-claim"><div><small>CLAIM / 01</small>small><p>Python proficiency ≥ Advanced</p>p></div>div><b>✓ Shared</b>b></div>div><div className="proof-claim"><div><small>CLAIM / 02</small>small><p>Security+ certification</p>p></div>div><b>✓ Shared</b>b></div>div><div className="proof-claim" style={{opacity:.55}}><div><small>CLAIM / 03</small>small><p>Private claim locked</p>p></div>div><b>⌑ Locked</b>b></div>div><div className="proof-foot"><span>⌁ Commitment recorded</span>span><span>MIDNIGHT / TESTNET</span>span></div>div></div>div></div>div></section>section>
    
    </main>main>
    
  )
    
}</main>

